### ISSUE TITLE
Split flexi components into separate repositories

### ISSUE THREAD

**Issue by kybishop** [html-next/flexi#109]
Master issue for splitting flexi components into multiple repositories. The main flexi repository will present a dependency installer for all the components we break out. All the of the below will be defaults, with the exception of flexi-sustain.

### Part 1: Splitting the repos

- [x] flexi-config - the config blueprint, and the hooks relevant to it in index.js @kybishop
- [x] flexi-default-styles - Everything in `./addon/styles/`. `./lib/scss-variables-compiler.js` @kybishop #112
- [x] flexi-dsl -  Everything in `./dsl/`. @kybishop #112
- [x] flexi-layouts - https://github.com/html-next/flexi/pull/110 `Container` mixin and its implementers. Everything in `./lib/` besides `scss-variables-compiler.js`. The `device/layout service`. @rwwagner90
- [x] flexi-sustain - #106 @rwwagner90 

If you start splitting a component, edit the issue or add a comment so we know what's already being worked on.

### Part 2: Auditing the split repos for extraneous code

- [x] flexi
- [x] flexi-default-styles - Done
- [x] flexi-dsl - Done
- [x] flexi-layouts - Done
- [x] flexi-sustain - Done

### Part 3: wrapping up

- [x]  Spruce up the dependency installation process
- [x] Update the readme(s)
  - [x] flexi-default-styles
  - [x] flexi-dsl
  - [x] flexi-layouts
  - [x] flexi-sustain

**Comment by kybishop** [comment]
@runspired we're happy to split what we think is appropriate, then ping you for PR, but you might save some review time by clarifying what's encapsulated in each repo. Feel free to edit the above issue with pointers, else we'll see you on the PR side ;)

**Comment by kybishop** [comment]
All libs split! Beta will begin shortly for 2.0.0
