### ISSUE TITLE
Roadmap to v3 (Embroider, Engine, Fastboot and Ember 4.0 support)

### ISSUE THREAD

**Issue by runspired** [html-next/flexi#181]
Opening this ticket to begin building out the requirements for a v3 to support the best in modern ember.

- [ ] replace greenkeeper with **dependabot**
- [ ] tests (regular + render-diff) for **embroider**
- [ ] tests (regular + render-diff) for **engines**
- [ ] tests (regular + render-diff) for **fastboot**
- [ ] update layout syntax components to make use of angle bracket components to minimize build time shenanigans
- [ ] consider tailwind or css-blocks oriented approach as the default

**Comment by eliel-jr** [comment]
news for this? this addon not compatible with ember 3.28 +

**Comment by runspired** [comment]
@eliel-jr no work done yet but getting close to starting

**Comment by runspired** [comment]
@eliel-jr would you be interested in helping? if so ping me in discord.
